version: '3.7'
services:
  kafka:
    image: bitnami/kafka:latest  # Use Bitnami Kafka which supports KRaft mode
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes  # Enable KRaft mode (no ZooKeeper required)
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    volumes:
      - ./kafka_data:/bitnami/kafka
    networks:
      - kafka-network

  data-gen-producer:
    build:
      context: ./data
    container_name: data-gen
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092 
    ports:
      - "8080:8080"
    networks:
      - kafka-network 
    command: python synthetic_data_gen.py
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - kafka-network 
  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    container_name: logstash
    depends_on:
      - kafka
      - elasticsearch
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - kafka-network
  
networks:
  kafka-network: 
    driver: bridge